# Generated by Django 3.1.2 on 2020-11-27 09:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('interview', '0002_auto_20201127_1006'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='candidate',
            options={'permissions': [('export', 'Can export candidate list'),
                                     ('notify', 'notify interviewer for candidate review')],
                     'verbose_name': '应聘者', 'verbose_name_plural': '应聘者'},
        ),
    ]
